import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Redis } from "@upstash/redis";
import OutputCard from "@/components/OutputCard";

export const runtime = "nodejs";

interface SharedPost {
  post: string;
  pattern: string;
  createdAt: string;
}

async function getShared(id: string): Promise<SharedPost | null> {
  if (!process.env.UPSTASH_REDIS_REST_URL || !process.env.UPSTASH_REDIS_REST_TOKEN) {
    return null;
  }
  // Guard against key injection from the path param
  if (!/^[A-Za-z0-9_-]{4,16}$/.test(id)) return null;
  try {
    const redis = Redis.fromEnv();
    const raw = await redis.get<SharedPost | string>(`share:${id}`);
    if (!raw) return null;
    return typeof raw === "string" ? (JSON.parse(raw) as SharedPost) : raw;
  } catch {
    return null;
  }
}

interface Props {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  const shared = await getShared(id);
  if (!shared) return { title: "Post not found" };

  const excerpt =
    shared.post.length > 160 ? `${shared.post.slice(0, 157)}...` : shared.post;

  return {
    title: "Someone shipped a thought-leadership piece",
    description: excerpt,
    openGraph: {
      title: "LinkedIn Shitpost Generator",
      description: excerpt,
      type: "article",
    },
    twitter: {
      card: "summary",
      title: "LinkedIn Shitpost Generator",
      description: excerpt,
    },
  };
}

export default async function SharedPostPage({ params }: Props) {
  const { id } = await params;
  const shared = await getShared(id);
  if (!shared) notFound();

  return (
    <main className="min-h-screen bg-[#F3F2EF] py-10 px-4">
      <div className="max-w-[555px] mx-auto space-y-6">
        <OutputCard
          pattern={shared.pattern}
          label={shared.pattern}
          emoji=""
          color=""
          post={shared.post}
        />
        <p className="text-center text-sm text-[#666]">
          Generated by the{" "}
          <Link href="/" className="text-[#0A66C2] font-semibold hover:underline">
            LinkedIn Shitpost Generator
          </Link>
          . Make your own.
        </p>
      </div>
    </main>
  );
}
